site_name: Documentation
site_url: http://localhost:8824/
use_directory_urls: false

nav:
  - Home: index.md

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.emoji
  - codehilite
  - fenced_code
  - def_list
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

theme:
  name: material
  palette:
    primary: blue
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.expand